/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ball.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useSphere } from '@react-three/cannon';

export function Ball(props) {
  const { nodes, materials } = useGLTF('/assets/models/ball.glb');

  const [meshRef] = useSphere(
    () => ({
      args: [0.15],
      mass: 3,
      ...props,
    }),
    useRef(null)
  );

  return (
    <group ref={meshRef}>
      <group scale={0.15} position={[0, -0.153, -0.004]}>
        <mesh
          geometry={nodes.beach_ball_red_0_1.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.beach_ball_red_0_2.geometry}
          material={materials.blue}
        />
        <mesh
          geometry={nodes.beach_ball_red_0_3.geometry}
          material={materials.white}
        />
        <mesh
          geometry={nodes.beach_ball_red_0_4.geometry}
          material={materials.yellow}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/assets/models/ball.glb');
